# Generated by Django 4.2.3 on 2023-08-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='Team',
        ),
    ]
